id: P000693
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:26.279777
source_metadata:
  id: bdr:W1KG1578
  title: ཀུན་བཟང་བླ་མའི་ཞལ་ལུང་།
  author: ''
  volumes:
    5b02f2bca92d422ea684b73d61b7c767:
      image_group_id: I1KG1641
      title: ''
      volume_number: 1
      total_pages: 556
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
